name: codecov--onPush

on:
  push:
    branches:
      - master

jobs:
  codecov--onPublished:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - run: yarn

      - run: yarn test:cov

      - uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}